openapi: 3.2.0
info:
  title: INRIX Parkme Accounts API
  description: INRIX Parkme Web Service API
  contact:
    email: support@inrix.com
  version: v1
servers:
- url: https://parking-api.inrix.com/
security:
- Basic: []
tags:
- name: Accounts
paths:
  /accounts/mobile/delete/:
    parameters: []
    delete:
      operationId: accounts_mobile_delete_delete
      description: Endpoint for deleting a user account from mobile app
      responses:
        '204':
          description: ''
      tags:
      - Accounts
      summary: Accounts mobile delete delete
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
